### ISSUE TITLE
Software paper edits

### ISSUE THREAD

**Issue by JeffreyCHoover** [ForsbergPyschometrics/D3mirt#13]
Your paper read well. The one piece of feedback that I would offer is that it appears your software paper would be strengthened by including a comparison to other software/packages performing similar functions and describing how your package provides functionality above and beyond those other softwares/packages.

As a minor point, I think the in-text citation for Forsberg & Sjöberg needs to be updated. It currently reads as just "Forsberg (2024)".

**Comment by ForsbergPsychometrics** [comment]
A brief software comparison has been added and the reference is fixed in the latest version of the paper.

**Comment by JeffreyCHoover** [comment]
Looks great! I think this issue can be closed down.
