### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JeffreyCHoover** [ForsbergPyschometrics/D3mirt#14]
A couple minor suggestions for improvements to the package documentation:

- including unit tests to verify the performance of the package's functions
- including a note and guidelines in the README for those wishing to contribute to the package
- reiterating the statement of need from the software paper in the package README
- ensuring that the examples in the function documentation are stand-alone; for instance, the example for `summary.modid()` begins with `g <- modid(x)` but users would have to either run the other examples first to have the correct object for `x` or they have to reference other parts of the package to correctly specify `x`

**Comment by ForsbergPsychometrics** [comment]
- Test units have been added (see comment regarding issue "Functionality")
- Guidelines for contributing to code have been added to README under the heading "Getting Help, Feedback, and Questions"
- Most of the statement of need is in the README but is compressed. This will be addressed again after revising the paper.
- Examples in the documentation are now standalone.

**Comment by JeffreyCHoover** [comment]
This looks great! Thanks for considering these! As far as my original concerns, I think this issue is ready to be closed.
