### ISSUE TITLE
DESCRIPTION minimum R version 

### ISSUE THREAD

**Issue by hendr1km** [ForsbergPyschometrics/D3mirt#18]
The minimum R version in your Description file is R (>= 3.5.0), although mirt (your dependency) has a minimum R version of (>= 3.6.0). I do not know if there are significant changes between those versions, but I would rather change it if you keep the dependency.

**Comment by ForsbergPsychometrics** [comment]
The description file now has R at (>= 3.6.0), and the mirt package has been moved to imports in the description file because the D3mirt package uses fairly few functions from mirt.
